### ISSUE TITLE
Add support for pre/post execution

### ISSUE THREAD

**Issue by efiShtain** [allcloud-io/clisso#224]
When running clisso, on successful run, it would be useful to add user scripts that can use the credentials and do some more things

**Comment by efiShtain** [comment]
@bitte-ein-bit 
I'll give you an example,
In my setup (currently), I use gradle and a global gradle properties file holding aws credentials (for local development)
every time I run clisso, I also need to patch the global gradle.properties file to have the updated credentials

so I have a script the use aws cli to fetch the relevant credentials and update gradle properties
but I have to remember to run it every time (or use the terminal history)

the feature request is to allow me configure postExecution scripts that would be called after successful run

to be more explicit, I want to be able to run something like
```bash
clisso apps <my_app> add-post-execution-script <script_unique_name> <my_script_path>
```

so everytime I run clisso for my app and it succeed, it will call my script with the credentials
```bash
<my_script_path> access_key secret_key session_token
```


removing a script is simple

```bash
clisso apps <my_app> remove-post-execution-script <script_unique_name>
```

**Comment by bitte-ein-bit** [comment]
Hey,

understood your use case. I'm afraid this is bad practice. Instead of what you describe please look into using `AwsImAuthentication` with gradle. https://stackoverflow.com/questions/41792197/getting-aws-role-credentials-in-gradle should get you started.

The idea here: instead of static credentials copied over into a gradle file, you use an AWS profile reference. This way, you can e.g. also use services like AWS CodeBuild without major build pipeline changes.

**Comment by bitte-ein-bit** [comment]
Closing the issue for now.
