### ISSUE TITLE
Extract ARNs from SAML on onelogin

### ISSUE THREAD

**Issue by jspc** [allcloud-io/clisso#49]
Given that onelogin/ aws saml reponses return necessary ARNs, extract these and use them to generate credentials rather than hardcoding them in config.

Where multiple ARNs exist, such as is the case with the [onelogin multi-account app](https://onelogin.service-now.com/support/?id=kb_article&sys_id=66a91d03db109700d5505eea4b9619a5), present a form for a user to select from.

This approach is used in onelogin reference implementations of pulling AWS creds:

1. https://developers.onelogin.com/api-docs/1/samples/aws-cli
1. https://github.com/onelogin/onelogin-aws-cli-assume-role/blob/master/onelogin-aws-assume-role-cli/src/main/java/com/onelogin/aws/assume/role/cli/OneloginAWSCLI.java#L222-L241

**Comment by johananl** [comment]
We've been looking for a way to avoid having to deal with ARNs in the config and could not find a good solution until now. In order to perform an [AssumeRoleWithSAML](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithSAML.html) operation, the principal ARN and role ARN must be specified.

Are you saying we can extract this information from the response [here](https://developers.onelogin.com/api-docs/1/saml-assertions/generate-saml-assertion)?

**Comment by jspc** [comment]
Yep- the SAML body contains ARNs, take a look at:

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_saml_assertions.html

(There are no anchors in that doc, search for `An Attribute element with the Name attribute set to https://aws.amazon.com/SAML/Attributes/Role`)

**Comment by johananl** [comment]
Interesting. I'll take a look soon when I get to it. I'd definitely love to get rid of as much config as possible.

**Comment by jspc** [comment]
I'm going to tackle this today when I've finished off
https://github.com/allcloud-io/clisso/issues/50

**Comment by johananl** [comment]
Fixed in https://github.com/allcloud-io/clisso/pull/52.
