### ISSUE TITLE
Error should be handled first

### ISSUE THREAD

**Issue by johananl** [allcloud-io/clisso#83]
https://github.com/allcloud-io/clisso/blob/3beeddd3624fa0c04c16127d19285bfdc03846be/aws/aws.go#L40-L47

We should first return on error, then continue normal flow without `else`.

**Comment by allcloud-jonathan** [comment]
I agree about switch the order. 

I disagree about returning an error. Current behaviour just continues with the next entry in the list and tries to clean it up. I think this is beneficial because it removes everything we can manage and keeps the rest untouched. The "rest" could be created by a different tool that has the same key but incompatible syntax. WDYT?

**Comment by johananl** [comment]
Ah, sorry. I didn't mean to change the behavior here. It's just a Golang idiom that should be used as-is in most cases:

```go
err := something()
if err != nil {
    return err
}
// Continue normally.
```

So yes, by "return" I meant "handle the error", whatever that is in the specific use case.
